# Generated by Django 2.1.7 on 2019-08-26 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20190725_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(default='3fb5c41d-be91-487e-baec-b86a30685207', on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
