# Generated by Django 2.1.7 on 2019-08-28 21:12

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190827_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=users.models.generate_token, max_length=512, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fees_paypal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('paypal_buyer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_transaction_id_organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('paypal_approval_url', models.CharField(blank=True, max_length=1500, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_source_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('fees_stripe', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('payment_method', models.CharField(choices=[('paypal', 'paypal'), ('stripe_creditcard', 'stripe_creditcard'), ('stripe_sofort', 'stripe_sofort'), ('stripe_giropay', 'stripe_giropay'), ('invoice', 'invoice'), ('rausweis', 'rausweis'), ('generated', 'generated')], default='paypal', max_length=100)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='users.Wallet')),
            ],
        ),
    ]
