# Generated by Django 2.1.7 on 2019-09-19 14:14

from django.db import migrations, models
import django.db.models.deletion
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=users.models.generate_code, max_length=512, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_valid_until', models.DateTimeField()),
                ('amount', models.BigIntegerField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='users.Charge')),
            ],
        ),
    ]
