# Generated by Django 2.1.7 on 2019-09-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='date_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
