# Generated by Django 2.1.7 on 2019-09-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190919_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='date_valid_until',
            new_name='used_at',
        ),
        migrations.AddField(
            model_name='voucher',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='users.Charge'),
        ),
    ]
