# Generated by Django 2.1.7 on 2019-12-05 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_wristband_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wristband',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wristband',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wristband',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DISABLED', 'DISABLED')], default=datetime.datetime(2019, 12, 5, 11, 9, 44, 879968, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
