# Generated by Django 2.1.7 on 2020-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191205_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
