# Generated by Django 2.1.7 on 2020-01-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_wallet_private_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='private_key',
            new_name='priv_key',
        ),
    ]
