# Generated by Django 2.1.7 on 2020-01-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200114_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('ready', 'ready'), ('success', 'success'), ('error', 'error')], default='pending', max_length=255),
        ),
    ]
