# Generated by Django 2.1.7 on 2019-07-25 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festival', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='festivals', to=settings.AUTH_USER_MODEL),
        ),
    ]
