# Generated by Django 2.1.7 on 2019-04-09 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('label', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], max_length=32)),
                ('error_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('payload', models.TextField()),
                ('date_broadcast', models.DateTimeField(blank=True, null=True)),
                ('signed_tx', models.TextField()),
                ('tx_hash', models.CharField(max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Invoice')),
            ],
        ),
    ]
