# Generated by Django 2.1.7 on 2019-07-25 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_auto_20190725_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('product_price', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True)),
                ('product_picture', models.CharField(blank=True, max_length=255)),
                ('count', models.IntegerField()),
                ('total_amount', models.BigIntegerField()),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('ready', 'ready'), ('success', 'success'), ('error', 'error')], max_length=255)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='shop.Order'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_items', to='shop.Product'),
        ),
    ]
