# Generated by Django 2.1.7 on 2019-07-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190725_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
