# Generated by Django 2.1.7 on 2019-08-21 13:57

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190819_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, default=shop.models.generate_pickup_code, max_length=255),
        ),
    ]
