# Generated by Django 2.1.7 on 2019-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_pickup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='product_icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
