# Generated by Django 2.1.7 on 2019-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190822_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pub_key',
            field=models.CharField(default='NOT_SET', max_length=255),
            preserve_default=False,
        ),
    ]
