# Generated by Django 2.1.7 on 2019-08-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_app_id'),
        ('shop', '0010_shop_pub_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet',
            field=models.ForeignKey(default='03ccee0d-ccc7-4fe1-aac3-a305eebdd607', on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='users.Wallet'),
            preserve_default=False,
        ),
    ]
