# Generated by Django 2.1.7 on 2019-09-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='blockchain_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
